version: "3.9" # Use the latest version of Docker Compose

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085" # Map host port 8085 to container port 8085
    volumes:
      - .:/usr/src/app # Mount the current directory to the app directory inside the container
      - /usr/src/app/node_modules # Prevent overwriting node_modules
    environment:
      NODE_ENV: development # Use development mode
    # command: ["npm", "run", "dev"] # Override CMD to run in development mode
    # depends_on:
      # - db

  # db:
  #   image: postgres:15-alpine # Use the latest PostgreSQL image
  #   container_name: postgres_db
  #   restart: always
  #   ports:
  #     - "5432:5432" # Map host port 5432 to container port 5432
  #   environment:
  #     POSTGRES_USER: appuser
  #     POSTGRES_PASSWORD: securepassword
  #     POSTGRES_DB: appdb
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data # Persist PostgreSQL data

volumes:
  postgres_data: {}
